/**
 * 万能百宝箱 v5.0 - 工具数据
 * 任务驱动型效率工具平台
 * 7大任务分类，每个分类精选最实用工具
 */

const CATEGORIES = [
    {
        id: 'writing',
        name: '写作创作',
        icon: '✍️',
        color: '#FF6B6B',
        gradient: 'linear-gradient(135deg, #FF6B6B, #FF8E8E)',
        desc: '文档写作、文案创作、内容排版',
        tags: ['文档', '排版', '写作', '文案', '笔记']
    },
    {
        id: 'design',
        name: '设计媒体',
        icon: '🎨',
        color: '#4ECDC4',
        gradient: 'linear-gradient(135deg, #4ECDC4, #6EE7DE)',
        desc: '图片设计、视频剪辑、海报制作',
        tags: ['设计', '图片', '视频', '海报', 'PPT']
    },
    {
        id: 'coding',
        name: '编程开发',
        icon: '💻',
        color: '#45B7D1',
        gradient: 'linear-gradient(135deg, #45B7D1, #65D7F1)',
        desc: '代码编写、项目部署、技术学习',
        tags: ['编程', '开发', '部署', 'API', '开源']
    },
    {
        id: 'office',
        name: '办公数据',
        icon: '📊',
        color: '#96CEB4',
        gradient: 'linear-gradient(135deg, #96CEB4, #B6EED4)',
        desc: '表格处理、数据分析、流程协作',
        tags: ['表格', '数据', '协作', 'PDF', '流程图']
    },
    {
        id: 'learning',
        name: '学习研究',
        icon: '📚',
        color: '#FFEAA7',
        gradient: 'linear-gradient(135deg, #F9CA24, #FFEAA7)',
        desc: '学术搜索、知识管理、考试备考',
        tags: ['学术', '论文', '考试', '知识', '搜索']
    },
    {
        id: 'career',
        name: '求职职场',
        icon: '💼',
        color: '#DDA0DD',
        gradient: 'linear-gradient(135deg, #A29BFE, #DDA0DD)',
        desc: '简历制作、面试准备、职场提升',
        tags: ['简历', '面试', '求职', '职场', '公考']
    },
    {
        id: 'ai',
        name: 'AI 工具',
        icon: '🤖',
        color: '#FD79A8',
        gradient: 'linear-gradient(135deg, #FD79A8, #FF9FF3)',
        desc: 'AI对话、AI写作、AI绘画、AI编程',
        tags: ['AI', 'ChatGPT', '绘画', '写作', '智能']
    }
];

const TOOLS = [
    // ========================
    // ✍️ 写作创作
    // ========================
    {
        id: 'notion',
        name: 'Notion',
        category: 'writing',
        url: 'https://www.notion.so',
        icon: 'https://www.notion.so/images/favicon.ico',
        desc: 'All-in-one 工作空间，支持文档、知识库、项目管理、数据库等',
        tags: ['笔记', '知识库', '文档', '协作', '项目管理'],
        pricing: 'freemium',      // free | freemium | paid
        pricingText: '个人免费',
        difficulty: 2,            // 1-5 星
        audience: '所有人',
        audienceTags: ['学生', '白领', '团队'],
        hot: true,
        featured: true,
        related: ['yuque', 'feishu']
    },
    {
        id: 'yuque',
        name: '语雀',
        category: 'writing',
        url: 'https://www.yuque.com',
        icon: 'https://gw.alipayobjects.com/zos/bmw-prod/1e1fd6e2-0a25-4676-834a-2e1b97f7e530/favicon-32x32.png',
        desc: '阿里出品的知识管理与协作平台，支持文档、表格、思维导图',
        tags: ['笔记', '知识库', '文档', '协作', '思维导图'],
        pricing: 'freemium',
        pricingText: '基础免费',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['学生', '白领', '团队'],
        hot: true,
        featured: true,
        related: ['notion', 'mubu']
    },
    {
        id: 'feishu',
        name: '飞书文档',
        category: 'writing',
        url: 'https://www.feishu.cn',
        icon: 'https://lf3-static.bytednsdoc.com/obj/eden-cn/hpezv_lm_qj/font/favicon_v2_180_180.ico',
        desc: '字节跳动出品的新一代协作文档，支持多人实时编辑、评论',
        tags: ['文档', '协作', '表格', '在线编辑', '办公'],
        pricing: 'freemium',
        pricingText: '基础免费',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['白领', '团队', '远程办公'],
        hot: true,
        related: ['notion', 'yuque']
    },
    {
        id: 'typora',
        name: 'Typora',
        category: 'writing',
        url: 'https://typora.io',
        icon: 'https://typora.io/img/favicon-64.png',
        desc: '极简 Markdown 编辑器，所见即所得，支持导出 PDF/Word/HTML',
        tags: ['Markdown', '写作', '笔记', '导出'],
        pricing: 'paid',
        pricingText: '$14.99 买断',
        difficulty: 2,
        audience: '技术用户',
        audienceTags: ['程序员', '博主', '学生'],
        hot: false,
        related: ['obsidian', 'marktext']
    },
    {
        id: 'obsidian',
        name: 'Obsidian',
        category: 'writing',
        url: 'https://obsidian.md',
        icon: 'https://obsidian.md/favicon.ico',
        desc: '本地优先的双链笔记工具，知识图谱可视化，插件生态丰富',
        tags: ['笔记', '双链', '知识图谱', '本地', '插件'],
        pricing: 'freemium',
        pricingText: '个人免费',
        difficulty: 3,
        audience: '深度用户',
        audienceTags: ['研究者', '作家', '学生'],
        hot: true,
        related: ['notion', 'typora', 'logseq']
    },
    {
        id: 'marktext',
        name: 'MarkText',
        category: 'writing',
        url: 'https://github.com/marktext/marktext',
        icon: 'https://github.com/marktext/marktext/raw/master/resources/icons/marktext.png',
        desc: '免费开源的 Markdown 编辑器，支持数学公式、代码高亮',
        tags: ['Markdown', '开源', '免费', '写作'],
        pricing: 'free',
        pricingText: '完全免费',
        difficulty: 2,
        audience: '技术用户',
        audienceTags: ['程序员', '学生', '开源爱好者'],
        hot: false,
        related: ['typora', 'obsidian']
    },
    {
        id: 'logseq',
        name: 'Logseq',
        category: 'writing',
        url: 'https://logseq.com',
        icon: 'https://logseq.com/img/favicon.ico',
        desc: '隐私优先的大纲笔记工具，支持双链、PDF标注、知识图谱',
        tags: ['笔记', '双链', '大纲', '隐私', 'PDF'],
        pricing: 'free',
        pricingText: '完全免费',
        difficulty: 3,
        audience: '深度用户',
        audienceTags: ['研究者', '学生', '隐私关注者'],
        hot: false,
        related: ['obsidian', 'notion']
    },
    {
        id: 'mubu',
        name: '幕布',
        category: 'writing',
        url: 'https://mubu.com',
        icon: 'https://mubu.com/favicon.ico',
        desc: '极简大纲笔记工具，一键生成思维导图，适合整理思路',
        tags: ['大纲', '思维导图', '笔记', '整理'],
        pricing: 'freemium',
        pricingText: '基础免费',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['学生', '白领', '策划'],
        featured: true,
        related: ['yuque', 'xmind']
    },

    // ========================
    // 🎨 设计媒体
    // ========================
    {
        id: 'canva',
        name: 'Canva 可画',
        category: 'design',
        url: 'https://www.canva.cn',
        icon: 'https://static.canva.cn/static/images/favicon-1.ico',
        desc: '在线设计平台，海量模板，零基础也能做出专业设计',
        tags: ['设计', '模板', '海报', 'PPT', '社交媒体'],
        pricing: 'freemium',
        pricingText: '基础免费',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['小白', '运营', '自媒体'],
        hot: true,
        featured: true,
        related: ['figma', 'chuangkit']
    },
    {
        id: 'figma',
        name: 'Figma',
        category: 'design',
        url: 'https://www.figma.com',
        icon: 'https://static.figma.com/app/icon/1/favicon.ico',
        desc: '协作型 UI 设计工具，支持实时协作、组件库、原型设计',
        tags: ['UI设计', '原型', '协作', '组件库', '界面'],
        pricing: 'freemium',
        pricingText: '个人免费',
        difficulty: 3,
        audience: '设计师',
        audienceTags: ['UI设计师', '产品经理', '前端'],
        hot: true,
        related: ['canva', 'mastergo']
    },
    {
        id: 'mastergo',
        name: 'MasterGo',
        category: 'design',
        url: 'https://mastergo.com',
        icon: 'https://static.mastergo.com/favicon.ico',
        desc: '国产在线设计工具，Figma 替代品，中文体验好',
        tags: ['UI设计', '原型', '协作', '国产', '免费'],
        pricing: 'free',
        pricingText: '完全免费',
        difficulty: 3,
        audience: '设计师',
        audienceTags: ['UI设计师', '产品经理', '前端'],
        hot: true,
        related: ['figma', 'pixso']
    },
    {
        id: 'chuangkit',
        name: '创客贴',
        category: 'design',
        url: 'https://www.chuangkit.com',
        icon: 'https://static.chuangkit.com/favicon.ico',
        desc: '中文在线设计平台，模板丰富，适合海报、公众号配图',
        tags: ['设计', '模板', '海报', '公众号', '名片'],
        pricing: 'freemium',
        pricingText: '基础免费',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['运营', '自媒体', '小商家'],
        related: ['canva']
    },
    {
        id: 'removebg',
        name: 'Remove.bg',
        category: 'design',
        url: 'https://www.remove.bg',
        icon: 'https://www.remove.bg/favicon.ico',
        desc: 'AI 一键抠图，5秒去除背景，效果惊艳',
        tags: ['抠图', 'AI', '背景', '图片处理'],
        pricing: 'freemium',
        pricingText: '免费（有水印）',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['电商', '自媒体', '设计师'],
        hot: true,
        related: ['palettefm']
    },
    {
        id: 'palettefm',
        name: 'Palette.fm',
        category: 'design',
        url: 'https://palette.fm',
        icon: '🤖',
        desc: 'AI 自动给黑白老照片上色，效果逼真',
        tags: ['上色', 'AI', '老照片', '图片处理'],
        pricing: 'freemium',
        pricingText: '基础免费',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['摄影', '修图', '怀旧'],
        related: ['removebg']
    },
    {
        id: 'capcut',
        name: '剪映',
        category: 'design',
        url: 'https://www.capcut.cn',
        icon: 'https://lf-cdn-tos.bytescm.com/obj/static/capcut-pc/ide-static-website/favicon_v2.ico',
        desc: '字节跳动出品的视频剪辑工具，模板丰富，零门槛上手',
        tags: ['视频剪辑', '模板', '字幕', '特效', '短视频'],
        pricing: 'freemium',
        pricingText: '基础免费',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['短视频', '自媒体', 'Vlog'],
        hot: true,
        featured: true,
        related: ['douxin']
    },
    {
        id: 'tinypng',
        name: 'TinyPNG',
        category: 'design',
        url: 'https://tinypng.com',
        icon: 'https://tinypng.com/images/favicon.ico',
        desc: '智能压缩 PNG/JPEG 图片，体积减小 60-80%，画质几乎无损',
        tags: ['压缩', '图片', '优化', 'PNG', 'JPEG'],
        pricing: 'freemium',
        pricingText: '免费（每月20张）',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['前端', '运营', '设计师'],
        hot: true,
        related: ['squoosh']
    },
    {
        id: 'squoosh',
        name: 'Squoosh',
        category: 'design',
        url: 'https://squoosh.app',
        icon: 'https://squoosh.app/favicon.ico',
        desc: 'Google 出品的图片压缩工具，支持多种格式对比',
        tags: ['压缩', '图片', 'Google', '优化'],
        pricing: 'free',
        pricingText: '完全免费',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['前端', '设计师'],
        related: ['tinypng']
    },

    // ========================
    // 💻 编程开发
    // ========================
    {
        id: 'github',
        name: 'GitHub',
        category: 'coding',
        url: 'https://github.com',
        icon: 'https://github.githubassets.com/favicons/favicon-dark.svg',
        desc: '全球最大的代码托管平台，开源社区，版本管理',
        tags: ['Git', '开源', '代码托管', '版本控制', '协作'],
        pricing: 'freemium',
        pricingText: '公开仓库免费',
        difficulty: 2,
        audience: '开发者',
        audienceTags: ['程序员', '开源爱好者', '团队'],
        hot: true,
        featured: true,
        related: ['gitlab', 'gitee']
    },
    {
        id: 'vscode',
        name: 'VS Code',
        category: 'coding',
        url: 'https://code.visualstudio.com',
        icon: 'https://code.visualstudio.com/favicon.ico',
        desc: '微软出品的轻量级代码编辑器，插件生态无敌',
        tags: ['编辑器', 'IDE', '插件', '调试', '开发'],
        pricing: 'free',
        pricingText: '完全免费',
        difficulty: 2,
        audience: '开发者',
        audienceTags: ['程序员', '学生', '全栈'],
        hot: true,
        featured: true,
        related: ['cursor', 'windsurf']
    },
    {
        id: 'cursor',
        name: 'Cursor',
        category: 'coding',
        url: 'https://cursor.sh',
        icon: 'https://cursor.sh/favicon.ico',
        desc: 'AI 驱动的代码编辑器，VS Code 增强版，内置 AI 编程助手',
        tags: ['AI', '编辑器', '编程助手', '代码补全'],
        pricing: 'freemium',
        pricingText: '基础免费',
        difficulty: 2,
        audience: '开发者',
        audienceTags: ['程序员', 'AI爱好者'],
        hot: true,
        related: ['vscode', 'windsurf']
    },
    {
        id: 'vercel',
        name: 'Vercel',
        category: 'coding',
        url: 'https://vercel.com',
        icon: 'https://vercel.com/favicon.ico',
        desc: '前端部署平台，一键部署 Next.js/React 等项目，免费额度大',
        tags: ['部署', '前端', 'Next.js', '服务器', 'CDN'],
        pricing: 'freemium',
        pricingText: 'Hobby 计划免费',
        difficulty: 2,
        audience: '前端开发者',
        audienceTags: ['前端', '全栈', '独立开发者'],
        hot: true,
        related: ['netlify', 'github-pages']
    },
    {
        id: 'netlify',
        name: 'Netlify',
        category: 'coding',
        url: 'https://www.netlify.com',
        icon: 'https://www.netlify.com/favicon.ico',
        desc: '静态网站部署平台，支持自动构建、表单处理、Serverless 函数',
        tags: ['部署', '静态网站', 'JAMstack', 'CI/CD'],
        pricing: 'freemium',
        pricingText: 'Starter 计划免费',
        difficulty: 2,
        audience: '前端开发者',
        audienceTags: ['前端', '静态站', '独立开发者'],
        related: ['vercel', 'github-pages']
    },
    {
        id: 'github-pages',
        name: 'GitHub Pages',
        category: 'coding',
        url: 'https://pages.github.com',
        icon: '🌐',
        desc: 'GitHub 免费静态网站托管，适合个人博客、项目文档',
        tags: ['部署', '静态网站', '免费', 'GitHub', '博客'],
        pricing: 'free',
        pricingText: '完全免费',
        difficulty: 2,
        audience: '开发者',
        audienceTags: ['程序员', '博主', '学生'],
        related: ['vercel', 'netlify']
    },
    {
        id: 'stackoverflow',
        name: 'Stack Overflow',
        category: 'coding',
        url: 'https://stackoverflow.com',
        icon: 'https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico',
        desc: '全球最大的编程问答社区，遇到 bug 先搜这里',
        tags: ['问答', '社区', '编程', '问题解决'],
        pricing: 'free',
        pricingText: '完全免费',
        difficulty: 1,
        audience: '开发者',
        audienceTags: ['程序员', '学生'],
        hot: true,
        related: ['segmentfault']
    },
    {
        id: 'segmentfault',
        name: '思否 SegmentFault',
        category: 'coding',
        url: 'https://segmentfault.com',
        icon: 'https://segmentfault.com/static/img/favicon.bcee2b8c.ico',
        desc: '中文技术问答社区，适合搜索中文编程问题',
        tags: ['问答', '社区', '中文', '技术'],
        pricing: 'free',
        pricingText: '完全免费',
        difficulty: 1,
        audience: '开发者',
        audienceTags: ['中文用户', '程序员'],
        related: ['stackoverflow']
    },
    {
        id: 'windsurf',
        name: 'Windsurf',
        category: 'coding',
        url: 'https://codeium.com/windsurf',
        icon: '🌊',
        desc: 'Codeium 出品的 AI IDE，流畅的 AI 编程体验，免费额度多',
        tags: ['AI', 'IDE', '编程助手', '免费'],
        pricing: 'freemium',
        pricingText: '免费额度多',
        difficulty: 2,
        audience: '开发者',
        audienceTags: ['程序员', 'AI爱好者'],
        hot: false,
        related: ['cursor', 'vscode']
    },

    // ========================
    // 📊 办公数据
    // ========================
    {
        id: 'excel-online',
        name: 'Excel Online',
        category: 'office',
        url: 'https://www.office.com/launch/excel',
        icon: 'https://www.office.com/favicon.ico',
        desc: '微软在线 Excel，支持实时协作，免费使用基础功能',
        tags: ['表格', 'Excel', '在线', '协作', '数据'],
        pricing: 'freemium',
        pricingText: '基础免费',
        difficulty: 2,
        audience: '所有人',
        audienceTags: ['白领', '财务', '学生'],
        hot: true,
        related: ['shimo', 'airtable']
    },
    {
        id: 'shimo',
        name: '石墨文档',
        category: 'office',
        url: 'https://shimo.im',
        icon: 'https://shimo.im/favicon.ico',
        desc: '国产在线协作文档，支持表格、文档、表单、幻灯片',
        tags: ['文档', '表格', '协作', '在线', '国产'],
        pricing: 'freemium',
        pricingText: '基础免费',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['白领', '团队', '远程办公'],
        related: ['feishu', 'excel-online']
    },
    {
        id: 'airtable',
        name: 'Airtable',
        category: 'office',
        url: 'https://airtable.com',
        icon: 'https://airtable.com/favicon.ico',
        desc: '电子表格+数据库混合体，强大的项目管理和小型数据库',
        tags: ['数据库', '表格', '项目管理', '自动化', '低代码'],
        pricing: 'freemium',
        pricingText: '基础免费',
        difficulty: 3,
        audience: '进阶用户',
        audienceTags: ['产品经理', '运营', '团队'],
        hot: true,
        related: ['shimo', 'notion']
    },
    {
        id: 'processon',
        name: 'ProcessOn',
        category: 'office',
        url: 'https://www.processon.com',
        icon: 'https://www.processon.com/favicon.ico',
        desc: '在线流程图工具，支持流程图、思维导图、UML、网络拓扑图',
        tags: ['流程图', '思维导图', 'UML', '原型', '图表'],
        pricing: 'freemium',
        pricingText: '免费（9个文件）',
        difficulty: 2,
        audience: '所有人',
        audienceTags: ['产品经理', '运营', '程序员'],
        hot: true,
        featured: true,
        related: ['drawio', 'mubu']
    },
    {
        id: 'drawio',
        name: 'draw.io',
        category: 'office',
        url: 'https://app.diagrams.net',
        icon: 'https://app.diagrams.net/favicon.ico',
        desc: '免费开源的在线绘图工具，流程图、架构图、网络拓扑图',
        tags: ['流程图', '架构图', '开源', '免费', '绘图'],
        pricing: 'free',
        pricingText: '完全免费',
        difficulty: 2,
        audience: '所有人',
        audienceTags: ['技术人', '产品经理', '架构师'],
        related: ['processon']
    },
    {
        id: 'ilovepdf',
        name: 'iLovePDF',
        category: 'office',
        url: 'https://www.ilovepdf.com',
        icon: 'https://www.ilovepdf.com/img/favicon.ico',
        desc: '一站式 PDF 工具箱，合并、拆分、压缩、转换、编辑',
        tags: ['PDF', '合并', '拆分', '转换', '编辑'],
        pricing: 'freemium',
        pricingText: '基础免费',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['白领', '学生', '所有人'],
        hot: true,
        related: ['smallpdf']
    },
    {
        id: 'smallpdf',
        name: 'Smallpdf',
        category: 'office',
        url: 'https://smallpdf.com',
        icon: 'https://smallpdf.com/favicon.ico',
        desc: '简洁的 PDF 在线工具，支持压缩、转换、编辑、签名',
        tags: ['PDF', '压缩', '转换', '签名', '编辑'],
        pricing: 'freemium',
        pricingText: '免费（每日2次）',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['白领', '学生'],
        related: ['ilovepdf']
    },
    {
        id: 'xmind',
        name: 'XMind',
        category: 'office',
        url: 'https://xmind.cn',
        icon: 'https://xmind.cn/favicon.ico',
        desc: '专业思维导图工具，界面美观，支持多种导图结构',
        tags: ['思维导图', '整理', '结构化', '笔记'],
        pricing: 'freemium',
        pricingText: '基础免费',
        difficulty: 2,
        audience: '所有人',
        audienceTags: ['学生', '产品经理', '策划'],
        hot: true,
        related: ['mubu', 'processon']
    },

    // ========================
    // 📚 学习研究
    // ========================
    {
        id: 'google-scholar',
        name: 'Google Scholar',
        category: 'learning',
        url: 'https://scholar.google.com',
        icon: 'https://scholar.google.com/favicon.ico',
        desc: '全球最大的学术搜索引擎，查找论文、引用、学术资源',
        tags: ['学术搜索', '论文', '引用', '科研'],
        pricing: 'free',
        pricingText: '完全免费',
        difficulty: 1,
        audience: '研究者',
        audienceTags: ['研究生', '博士生', '研究员'],
        hot: true,
        featured: true,
        related: ['zhihu', 'bilibili']
    },
    {
        id: 'zhihu',
        name: '知乎',
        category: 'learning',
        url: 'https://www.zhihu.com',
        icon: 'https://static.zhihu.com/heifetz/favicon.ico',
        desc: '中文知识问答社区，各行各业的深度讨论和专业回答',
        tags: ['问答', '知识', '讨论', '专业', '社区'],
        pricing: 'free',
        pricingText: '完全免费',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['所有人'],
        hot: true,
        related: ['bilibili', 'google-scholar']
    },
    {
        id: 'bilibili',
        name: '哔哩哔哩',
        category: 'learning',
        url: 'https://www.bilibili.com',
        icon: 'https://www.bilibili.com/favicon.ico',
        desc: 'B站不只是娱乐，还有海量免费优质教程和学习资源',
        tags: ['视频', '教程', '学习', '免费', '弹幕'],
        pricing: 'free',
        pricingText: '完全免费',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['学生', '自学者', '所有人'],
        hot: true,
        featured: true,
        related: ['zhihu', 'mooc']
    },
    {
        id: 'mooc',
        name: '中国大学MOOC',
        category: 'learning',
        url: 'https://www.icourse163.org',
        icon: 'https://www.icourse163.org/favicon.ico',
        desc: '国内最大的在线课程平台，985/211高校免费课程',
        tags: ['课程', '大学', '免费', '证书', '学分'],
        pricing: 'free',
        pricingText: '完全免费',
        difficulty: 1,
        audience: '学生',
        audienceTags: ['大学生', '高中生', '自学者'],
        hot: true,
        related: ['bilibili', 'coursera']
    },
    {
        id: 'coursera',
        name: 'Coursera',
        category: 'learning',
        url: 'https://www.coursera.org',
        icon: 'https://www.coursera.org/favicon.ico',
        desc: '全球顶级大学在线课程平台，可免费旁听课程',
        tags: ['课程', '名校', '证书', '国际化', '免费旁听'],
        pricing: 'freemium',
        pricingText: '可免费旁听',
        difficulty: 2,
        audience: '进阶学习者',
        audienceTags: ['大学生', '职场人', '留学生'],
        related: ['mooc', 'edx']
    },
    {
        id: 'wikipedia',
        name: '维基百科',
        category: 'learning',
        url: 'https://zh.wikipedia.org',
        icon: 'https://zh.wikipedia.org/favicon.ico',
        desc: '全球最大的免费百科全书，知识覆盖面最广',
        tags: ['百科', '知识', '参考', '多语言'],
        pricing: 'free',
        pricingText: '完全免费',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['所有人'],
        related: ['baike']
    },
    {
        id: 'baike',
        name: '百度百科',
        category: 'learning',
        url: 'https://baike.baidu.com',
        icon: 'https://baike.baidu.com/favicon.ico',
        desc: '中文百科全书，了解中国相关知识的首选',
        tags: ['百科', '中文', '知识', '参考'],
        pricing: 'free',
        pricingText: '完全免费',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['中文用户'],
        related: ['wikipedia']
    },
    {
        id: 'fenbi',
        name: '粉笔',
        category: 'learning',
        url: 'https://www.fenbi.com',
        icon: 'https://www.fenbi.com/favicon.ico',
        desc: '公务员/事业单位考试题库，智能刷题，实时模考',
        tags: ['公考', '刷题', '模拟', '题库', '事业单位'],
        pricing: 'freemium',
        pricingText: '部分免费',
        difficulty: 1,
        audience: '考生',
        audienceTags: ['考公', '考编', '学生'],
        hot: true,
        related: ['huatu']
    },

    // ========================
    // 💼 求职职场
    // ========================
    {
        id: 'jianliben',
        name: '简历本',
        category: 'career',
        url: 'https://www.jianliben.com',
        icon: 'https://www.jianliben.com/favicon.ico',
        desc: '在线简历制作工具，精美模板，一键导出PDF',
        tags: ['简历', '模板', 'PDF', '求职'],
        pricing: 'freemium',
        pricingText: '基础免费',
        difficulty: 1,
        audience: '求职者',
        audienceTags: ['应届生', '求职者'],
        hot: true,
        featured: true,
        related: ['zhipin', 'liepin']
    },
    {
        id: 'zhipin',
        name: 'BOSS直聘',
        category: 'career',
        url: 'https://www.zhipin.com',
        icon: 'https://www.zhipin.com/favicon.ico',
        desc: '直接和老板/HR在线聊天，求职效率高，岗位多',
        tags: ['求职', '招聘', '聊天', '岗位'],
        pricing: 'free',
        pricingText: '求职免费',
        difficulty: 1,
        audience: '求职者',
        audienceTags: ['求职者', '应届生', '跳槽者'],
        hot: true,
        related: ['liepin', 'lagou']
    },
    {
        id: 'liepin',
        name: '猎聘',
        category: 'career',
        url: 'https://www.liepin.com',
        icon: 'https://www.liepin.com/favicon.ico',
        desc: '中高端人才招聘平台，猎头服务，适合有经验的职场人',
        tags: ['求职', '猎头', '中高端', '招聘'],
        pricing: 'free',
        pricingText: '求职免费',
        difficulty: 1,
        audience: '求职者',
        audienceTags: ['有经验者', '跳槽者', '管理岗'],
        related: ['zhipin', 'lagou']
    },
    {
        id: 'lagou',
        name: '拉勾招聘',
        category: 'career',
        url: 'https://www.lagou.com',
        icon: 'https://www.lagou.com/favicon.ico',
        desc: '互联网行业招聘平台，技术岗位多，薪资透明',
        tags: ['求职', '互联网', '技术', '招聘', '薪资'],
        pricing: 'free',
        pricingText: '求职免费',
        difficulty: 1,
        audience: '互联网人',
        audienceTags: ['程序员', '产品经理', '设计师'],
        related: ['zhipin', 'liepin']
    },
    {
        id: 'niuke',
        name: '牛客网',
        category: 'career',
        url: 'https://www.nowcoder.com',
        icon: 'https://www.nowcoder.com/favicon.ico',
        desc: 'IT求职刷题神器，校招笔试/面试真题，大厂面经',
        tags: ['笔试', '面试', 'IT', '真题', '面经'],
        pricing: 'freemium',
        pricingText: '基础免费',
        difficulty: 2,
        audience: 'IT求职者',
        audienceTags: ['计算机学生', '应届生', '程序员'],
        hot: true,
        related: ['zhipin', 'lagou']
    },
    {
        id: 'huatu',
        name: '华图教育',
        category: 'career',
        url: 'https://www.huatu.com',
        icon: 'https://www.huatu.com/favicon.ico',
        desc: '公务员考试培训老品牌，线上线下课程齐全',
        tags: ['公考', '培训', '课程', '考试'],
        pricing: 'paid',
        pricingText: '付费课程',
        difficulty: 1,
        audience: '考公人',
        audienceTags: ['考公', '考编', '学生'],
        related: ['fenbi']
    },
    {
        id: 'wondercv',
        name: 'WonderCV 超级简历',
        category: 'career',
        url: 'https://www.wondercv.com',
        icon: 'https://www.wondercv.com/favicon.ico',
        desc: '专业简历模板，BAT设计师出品，排版简洁有力',
        tags: ['简历', '模板', '排版', '专业'],
        pricing: 'freemium',
        pricingText: '基础免费',
        difficulty: 1,
        audience: '求职者',
        audienceTags: ['应届生', '职场新人'],
        related: ['jianliben']
    },

    // ========================
    // 🤖 AI 工具
    // ========================
    {
        id: 'chatgpt',
        name: 'ChatGPT',
        category: 'ai',
        url: 'https://chat.openai.com',
        icon: 'https://chat.openai.com/favicon.ico',
        desc: 'OpenAI 出品的 AI 对话助手，写作、编程、翻译、分析全能',
        tags: ['AI对话', '写作', '编程', '翻译', '分析'],
        pricing: 'freemium',
        pricingText: 'GPT-4o-mini 免费',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['所有人'],
        hot: true,
        featured: true,
        related: ['claude', 'doubao', 'kimi']
    },
    {
        id: 'claude',
        name: 'Claude',
        category: 'ai',
        url: 'https://claude.ai',
        icon: 'https://claude.ai/favicon.ico',
        desc: 'Anthropic 出品的 AI 助手，长文本处理能力强，回答更有深度',
        tags: ['AI对话', '长文本', '分析', '写作', '编程'],
        pricing: 'freemium',
        pricingText: '基础免费',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['研究者', '作家', '程序员'],
        hot: true,
        related: ['chatgpt', 'kimi']
    },
    {
        id: 'kimi',
        name: 'Kimi',
        category: 'ai',
        url: 'https://kimi.moonshot.cn',
        icon: 'https://kimi.moonshot.cn/favicon.ico',
        desc: '月之暗面出品的中文 AI 助手，超长上下文，支持文件分析',
        tags: ['AI对话', '长文本', '文件分析', '中文', '搜索'],
        pricing: 'free',
        pricingText: '完全免费',
        difficulty: 1,
        audience: '中文用户',
        audienceTags: ['所有人', '研究者', '学生'],
        hot: true,
        featured: true,
        related: ['chatgpt', 'doubao', 'claude']
    },
    {
        id: 'doubao',
        name: '豆包',
        category: 'ai',
        url: 'https://www.doubao.com',
        icon: 'https://www.doubao.com/favicon.ico',
        desc: '字节跳动出品的 AI 助手，中文对话流畅，集成抖音生态',
        tags: ['AI对话', '中文', '搜索', '写作'],
        pricing: 'free',
        pricingText: '完全免费',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['所有人', '抖音用户'],
        hot: true,
        related: ['chatgpt', 'kimi', 'tongyi']
    },
    {
        id: 'tongyi',
        name: '通义千问',
        category: 'ai',
        url: 'https://tongyi.aliyun.com',
        icon: 'https://tongyi.aliyun.com/favicon.ico',
        desc: '阿里云出品的 AI 助手，集成阿里生态，代码能力强',
        tags: ['AI对话', '代码', '中文', '阿里'],
        pricing: 'free',
        pricingText: '完全免费',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['所有人', '阿里用户'],
        hot: true,
        related: ['doubao', 'wenxin']
    },
    {
        id: 'wenxin',
        name: '文心一言',
        category: 'ai',
        url: 'https://yiyan.baidu.com',
        icon: 'https://yiyan.baidu.com/favicon.ico',
        desc: '百度出品的 AI 助手，搜索能力强，支持图片生成',
        tags: ['AI对话', '搜索', '图片生成', '中文'],
        pricing: 'free',
        pricingText: '完全免费',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['所有人', '百度用户'],
        related: ['tongyi', 'doubao']
    },
    {
        id: 'midjourney',
        name: 'Midjourney',
        category: 'ai',
        url: 'https://www.midjourney.com',
        icon: '🎨',
        desc: 'AI 绘画天花板，生成惊艳的艺术级图片，Discord 驱动',
        tags: ['AI绘画', '艺术', '图片生成', '设计'],
        pricing: 'paid',
        pricingText: '$10/月起',
        difficulty: 3,
        audience: '设计师',
        audienceTags: ['设计师', '艺术创作者', 'AI爱好者'],
        hot: true,
        related: ['dalle', 'liblibai']
    },
    {
        id: 'dalle',
        name: 'DALL·E',
        category: 'ai',
        url: 'https://openai.com/dall-e-3',
        icon: '🖼️',
        desc: 'OpenAI 出品的 AI 绘画工具，文生图效果好，集成在 ChatGPT 中',
        tags: ['AI绘画', '文生图', 'OpenAI'],
        pricing: 'paid',
        pricingText: '需 ChatGPT Plus',
        difficulty: 1,
        audience: '所有人',
        audienceTags: ['所有人'],
        related: ['midjourney', 'liblibai']
    },
    {
        id: 'liblibai',
        name: 'LibLib AI',
        category: 'ai',
        url: 'https://www.liblib.art',
        icon: 'https://www.liblib.art/favicon.ico',
        desc: '国产 AI 绘画平台，免费使用 Stable Diffusion，中文友好',
        tags: ['AI绘画', 'Stable Diffusion', '免费', '中文'],
        pricing: 'freemium',
        pricingText: '有免费额度',
        difficulty: 2,
        audience: '创作者',
        audienceTags: ['设计师', '插画师', 'AI爱好者'],
        hot: true,
        related: ['midjourney', 'dalle']
    },
    {
        id: 'copilot',
        name: 'GitHub Copilot',
        category: 'ai',
        url: 'https://github.com/features/copilot',
        icon: '🤖',
        desc: 'AI 编程助手，实时代码补全，支持多种编程语言和 IDE',
        tags: ['AI编程', '代码补全', '开发', 'IDE'],
        pricing: 'paid',
        pricingText: '$10/月',
        difficulty: 2,
        audience: '开发者',
        audienceTags: ['程序员', '全栈'],
        hot: true,
        related: ['cursor', 'windsurf']
    }
];
